local theme = require("base46").get_colors("base_30")

return {
    LspSagaDiagnosticBorder = { link = "NormalNC" },
    LspSagaDiagnosticHeader = { fg = theme.purple },
    LspSagaDiagnosticTruncateLine = { link = "NormalNC" },
    LspFloatWinBorder = { link = "NormalNC" },
    LspSagaBorderTitle = { link = "Title" },
    TargetWord = { link = "Error" },
    ReferencesCount = { link = "Title" },
    ReferencesIcon = { link = "Special" },
    DefinitionCount = { link = "Title" },
    TargetFileName = { fg = theme.grey_fg },
    DefinitionIcon = { link = "Special" },
    ProviderTruncateLine = { link = "NormalNC" },
    SagaShadow = {},
    LspSagaFinderSelection = { link = "Search" },
    DiagnosticTruncateLine = { link = "NormalNC" },
    DiagnosticError = { link = "LspDiagnosticsDefaultError" },
    DiagnosticWarning = { link = "LspDiagnosticsDefaultWarning" },
    DiagnosticInformation = { link = "LspDiagnosticsDefaultInformation" },
    DiagnosticHint = { link = "LspDiagnosticsDefaultHint" },
    DefinitionPreviewTitle = { link = "Title" },
    LspSagaShTruncateLine = { link = "NormalNC" },
    LspSagaDocTruncateLine = { link = "NormalNC" },
    LineDiagTuncateLine = { link = "NormalNC" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionTruncateLine = { link = "NormalNC" },
    LspSagaCodeActionContent = { link = "Normal" },
    LspSagaRenamePromptPrefix = { fg = theme.purple },
    LspSagaRenameBorder = { bold = true },
    LspSagaHoverBorder = { bold = true },
    LspSagaSignatureHelpBorder = { bold = true },
    LspSagaCodeActionBorder = { bold = true },
    LspSagaAutoPreview = {},
    LspSagaDefPreviewBorder = { bold = true },
    LspLinesDiagBorder = { bold = true },
}